#!/bin/bash



#НЕОБХОДИМЫЕ ПЕРЕМЕННЫЕ
cmdLine="$1"
userName=`whoami`
icon="$appfolder/ChromePortable"
diagram=${appfolder%/App}
diagram="$diagram/Diagrams"
#Данные для телеграмм бота
sBotKey='bot1844208783:AAHnDQhkV7kARiLCyus0vxV8jQdAYy4TZcY'	#Ваш api ключ
nChatId='-1001460258261'									#Id получателя



function _Now {						#функция генерации текущего времени

	echo $(date +"%d.%m.%Y %H:%M:%S")

}

function BotMsg {					#функция отправки сообщений боту в телеграм

	local URL="https://api.telegram.org/$sBotKey/sendMessage"
	curl -s -X POST $URL -d chat_id="$nChatId" -d parse_mode=html -d disable_notification=$2 -d text="$1"

}

function FileReader {				#функция поиска строки в файле

	local sText="$1"				#Список строк
	local sSearchText="$2"			#Искомая строка
	while IFS= read -r line			#Перебираем строки
	do

		[ -z "`echo $line | grep $sSearchText`" ] || {
			#Если есть совпадение, выдаем строку
			auth=`echo $line | egrep -o "\w+[-]{0,1}\w{0,}" | head -1`
			[ "$auth" == "$sSearchText" ] || { continue; }
			echo "$line"

		}

	done < "$sText"

}

function Logger {					#функция отправки текста в логи

	local TIME=$(printf "%-19s" "$(_Now)")
	local ADDRES=$(printf "%-18s" "$1")
	local HOST=$(printf "%-20s" "$2")
	local USER=$(printf "%-42s" "$3")
	local ACT=$(printf "%-18s" "$4")
	echo "$TIME | $ADDRES | $HOST | $USER | $ACT"

}

function ChangesM {					#Функция прочитывания сообщений

	[ -e "$appfolder/httpN/system/temp/Changes/$name" ] && {	#Оповещаем пользователя

		#Ищем файлик-метку. Выводим содержимое и удаляем файлик
		changes=`cat "$appfolder/httpN/system/temp/Changes/$name"`
		zenity --info --title="Информация" --window-icon="$icon/GetStand.png" --text="$changes" --ellipsize --timeout=30
		rm "$appfolder/httpN/system/temp/Changes/$name"

	}

}

function Validator {				#Функция проверки строки по шаблону

	if [ -z `echo "$1" | egrep -o "$2"` ]
	then

		echo 1		#Строка не прошла шаблон

	else echo 0
	fi

}

function TrackBinFile {				#Функция запуска и слежения за приложением

	ping -c 3 -W 1 $address >/dev/null
	if [ $? != 0 ]	#Проверяем сеть. Если не пингуется хост или шлюз
	then

		message=`echo -e "👤$name\n️⚠️Неудачное подключение\n🖥️$hostName 🕹$1 ⏱$(_Now)"`
		BotMsg "$message" 0
		message=`Logger "$userName" "$hostName:$1" "$name" "Хост или шлюз не отвечает"`
		echo -e	"$message" >> "$appfolder/httpN/system/log/log.txt"
		zenity --error --title="Ошибка" --window-icon="$icon/GetStand.png" --text="Не удается подключиться к хосту\nОбратитесь в Отдел Тестирования" --ellipsize --timeout=3

	else									#Если пингуется, запускаем приложение

		$2$3 &								#Запускаем приложение и фиксируем его PID
		PID=$!
		message=`echo -e "👤$name\n️✅Подключился к хосту\n🖥️$hostName 🕹$1 ⏱$(_Now)"`
		BotMsg "$message" 0
		message=`Logger "$userName" "$hostName:$1" "$name" "Успешное подключение"`
		echo -e	"$message" >> "$appfolder/httpN/system/log/log.txt"
		#Запускаем сессию приложения
		t=0
		while true
		do

			sleep 1s							#Отсчитываем условную секунду
			t=$(($t + 1))
			#Условия окончания сессии
			if [ -z `ps --no-headers $PID` ]	#Если завершили процесс вручную
			then

				message=`echo -e "👤$name\n️⬅️Отключился от хоста\n🖥️$hostName 🕹$1 ⏱$(_Now)"`
				BotMsg "$message" 0
				message=`Logger "$userName" "$hostName:$1" "$name" "Завершение работы"`
				echo -e	"$message" >> "$appfolder/httpN/system/log/log.txt"
				break

			elif [ -e "$appfolder/httpN/system/temp/Sessions/UPDATE" ]	#Если начали обновление
			then

				zenity --warning --title="Предупреждение" --window-icon="$icon/GetStand.png" --text="Обновление системы. Сохраните работу\nПриложение закроется через минуту" --ellipsize --timeout=5
				j=0
				while [ $j -lt 55 ]
				do

					sleep 1s
					j=$(($j + 1))
					[ -z `ps --no-headers $PID` ] && { break; }
					[ -e "$appfolder/httpN/system/temp/Sessions/KILL" ] && { break; }

				done
				kill -9 $PID
				break

			elif [ $t == 30000 ]		#Если дождались таймаута
			then

				kill -9 $PID
				message=`echo -e "👤$name\n️⬅️Сессия завершена\n🖥️$hostName 🕹$1 ⏱$(_Now)"`
				BotMsg "$message" 0
				message=`Logger "$userName" "$hostName:$1" "$name" "Сессия завершена"`
				echo -e	"$message" >> "$appfolder/httpN/system/log/log.txt"
				zenity --warning --title="Предупреждение" --window-icon="$icon/GetStand.png" --text="Сессия $hostName:$1\nзавершена по таймауту" --ellipsize --timeout=3
				break

			fi

			#Функции, действующие во время сессии
			[ -e "$app/system/temp/Sessions/ONLINE" ] && {	#Говорим что онлайн

				#Создаем файлик-метку, обрабатываем его другой прогой, которая его удалит
				touch "$appfolder/httpN/system/temp/PIDS/$name.$hostName.$(($t/60))"

			}
			ChangesM

		done

	fi

}