#!/bin/bash



#НЕОБХОДИМЫЕ ПЕРЕМЕННЫЕ
appfolder=`realpath $0`
appfolder=${appfolder%/httpN/httpN_Linux}
. $appfolder/httpN/system/httpN_linux_lib
#Библиотека функций



#ПРОВЕРКА И ЗАПУСК BIN ФАЙЛА
[ -e "$appfolder/httpN/system/temp/Sessions/UPDATE" ] && {	#Проверка на обновления

	zenity --warning --title="Предупреждение" --window-icon="$icon/GetStand.png" --text="Ведутся технические работы\nПопробуйте позже" --ellipsize --timeout=3
	exit

}
[ -z "$cmdLine" ] && {										#Вызывается если нет аргументов

	#Строим окно для ввода данных
	input=$(zenity --entry --title="httpn запуск" --window-icon="$icon/GetStand.png" --width=256 --height=200 --text="Введите приложение VNC, KIT или SCP и \nхостнейм компьютера для подключения вручную\nПример: VNC default" --entry-text="Введите хостнейм" --ok-label="Запуск" --cancel-label="Выход")
	if [ $? == 0 ]		#Разбираем командную строку и запускаем подключение
	then

		cmdLine="httpn://"${input:0:3}" "${input#${input:0:4}}

	else exit;
	fi

}



#ПРОВЕРКА ИМЕНИ И ПРАВ ПОЛЬЗОВАТЕЛЯ ПО СПИСКУ АВТОРИЗАЦИИ
[ -e "/home/$userName/" ] || {								#Если имя или каталог не определился

	message=`echo -e "🛑<b>Ошибка конфигурации</b>\n❌Имя пользователя не определено\n⏱$(_Now)"`
	BotMsg "$message" 0
	message=`printf "%-19s" "$(_Now) | Имя пользователя не определено. Проверьте компьютер пользователя."`
	echo -e	"$message" >> "$appfolder/httpN/system/log/system.txt"
	zenity --error --title="Ошибка" --window-icon="$icon/GetStand.png" --text="Имя пользователя не определено\nОбратитесь в Отдел Тестирования" --ellipsize --timeout=3
	exit

}
autorizedUser="`FileReader $appfolder/httpN/system/USERS $userName`"	#Ищем пользователя в списке
#Захватим название выбранного пользователем компьютера в виде кода стойки-стенда.
hostName=`echo $cmdLine | sed "s/%20/ /"`
hostName=`echo ${hostName#${hostName:0:12}}`					#Выбираем имя компьютера
binFile=`echo $cmdLine | grep -Eo "VNC|KIT|SCP|FBC|ACH"`
	[ `echo ${#autorizedUser}` == 0 ] && {	#Если имя пользователя отсутствует в списке, заканчиваем работу

		message=`echo -e "👤<b>Неизвестный Пользователь</b>\n️⚠️Пытался подключиться к хосту\n🖥️$hostName 🕹$eks ⏱$(_Now)"`
		BotMsg "$message" 0
		message=`Logger "$userName" "$hostName:$binFile" "Неизвестный Пользователь(unknown)" "Неавторизованный вход"`
		echo -e	"$message" >> "$appfolder/httpN/system/log/log.txt"
		zenity --error --title="Ошибка" --window-icon="$icon/GetStand.png" --text="Авторизация не пройдена\nОбратитесь в Отдел Тестирования" --ellipsize --timeout=3
		exit

	}
#Выделяем имя пользователя из строки, которое будет использоваться в названии файлов
name=`echo "$autorizedUser" | egrep -o "[а-яА-Я]{1,}\s{1,}[а-яА-Я]{1,}\(\w+\)" | head -1`
ChangesM	#Проверяем наличие сообщений
	[ `echo $cmdLine | egrep -o "FBC"` == "FBC" ] && {		#Окошко для фидбека

		stend=`echo $cmdLine | sed "s/%20/ /"`
		stend=`echo ${stend#${stend:0:12}}`
		feedback=$(zenity --entry --title="Обратная связь" --window-icon="$icon/GetStand.png" --width=256 --height=200 --text="Все вопросы и предложения можете \nнаписать разработчику в этой форме\nРазработчик: Смирнов А.Д. ОТ" --entry-text="Введите ваше сообщение" --ok-label="Отправить" --cancel-label="Выход")
		[ $? == 0 ] || { exit; }
		AchievmentTracker "$name" 7
		message=`echo -e "@IllugiSven\n👤$name\n️⚠️Новый вопрос или предложение\n🖥️Стенд: $stend ⏱$(_Now)"`
		BotMsg "$message" 0
		message=`printf "%-19s" "$(_Now) | $name. Новый вопрос или предложение по стенду: $stend. $feedback"`
		echo -e	"$message" >> "$appfolder/httpN/system/log/system.txt"
		zenity --info --title="Информация" --window-icon="$icon/GetStand.png" --text="Ваше сообщение передано\nразработчику" --ellipsize --timeout=3
		exit

	}
	[ `echo $cmdLine | egrep -o "ACH"` == "ACH" ] && {		#Окошко для ачивов

		AchievmentTracker "$name" 1
		AchievmentTracker "$name" "show"
		exit

	}

#Проверим права на подключение. Если в строке не найдем имя компьютера или ADMIN, то выдаем ошибку.
	if [[ -z `echo $autorizedUser | grep "$hostName"` && -z `echo $autorizedUser | grep "ADMIN"` ]]
	then

		AchievmentTracker "$name" 9
		zenity --warning --title="Предупреждение" --window-icon="$icon/GetStand.png" --text="Недостаточно пользовательских прав\nна подключение к $hostName" --ellipsize --timeout=3
		exit

	fi



#ПОЛУЧЕНИЕ ИНФОРМАЦИИ О КОМПЬЮТЕРЕ СТЕНДА ИЗ КОМАНДНОЙ СТРОКИ ЗАПУСКА
namehost="`FileReader $appfolder/httpN/system/HOSTS $hostName`" 	#Получим строку с хостом и адресом
hn=`echo $namehost | egrep -o "\w+" | head -1`
#Ищем информацию о хосте из списка хостов
	if [[ -z "$namehost" || `echo "${#hn}"` != `echo "${#hostName}"` ]]	#Если имя не найдено
	then

		message=`echo -e "🛑<b>Ошибка конфигурации</b>\n️❌Имя компьютера не найдено\n🖥️$hostName ⏱$(_Now)"`
		BotMsg "$message" 0
		message=`printf "%-19s" "$(_Now) | Имя компьютера $hostName не найдено. Проверьте схему, список и строку запуска."`
		echo -e	"$message" >> "$appfolder/httpN/system/log/system.txt"
		zenity --error --title="Ошибка" --window-icon="$icon/GetStand.png" --text="Имя компьютера не найдено\nОбратитесь в Отдел Тестирования" --ellipsize --timeout=3
		exit

	fi
#Разбираем строку адреса или маршрута
#Проверим правильность ip-адрессов на соответствие частным сетям ipv4
#"^((10|192|127|169)\.){1}((25[0..5]|(2[0..4]\d|1{0,1}\d){0,1}\d)(\.?)){3}$" пропускает значащие нули
addcheck=`Validator "$namehost" "[A](([0-9]{1,3}\.){3}[0-9]{1,3})"`
portcheck=`Validator "$namehost" "[S][0-9]{2,5}"`
passcheck=`Validator "$namehost" "[#]\S+"`
	[[ $(($addcheck + $portcheck + $passcheck)) == 0 ]] || {

		message=`echo -e "🛑<b>Ошибка конфигурации</b>\n️❌Ошибка в списке хостов\n🖥️$hostName ⏱$(_Now)"`
		BotMsg "$message" 0
		message=`printf "%-19s" "$(_Now) | В записи адреса $hostName ошибка. Проверьте запись в списке хостов."`
		echo -e	"$message" >> "$appfolder/httpN/system/log/system.txt"
		zenity --error --title="Ошибка" --window-icon="$icon/GetStand.png" --text="Ошибка в списке хостов\nОбратитесь в Отдел Тестирования" --ellipsize --timeout=3
		exit

	}
addcheck=`echo "$namehost" | egrep -o "[A]((\w+\.){3}\w+)"`			#Получаем шаблон адреса
portcheck=`echo "$namehost" | egrep -o "[S][0-9]{2,5}"`				#Получаем шаблон порта
passcheck=`echo "$namehost" | egrep -o "[#]\S+"`					#Получаем шаблон пароля
address=`echo ${addcheck#${addcheck:0:1}}`							#Получаем адрес компьютера
port=`echo ${portcheck#${portcheck:0:1}}`							#Получаем порт компьютера
pass=`echo ${passcheck#${passcheck:0:1}}`							#Получаем пароль компьютера
pass=`echo "$pass" | base64 -d`
pass=`echo "$pass" | sed "s/$hostName//"`
pass=`echo "$pass" | sed "s/$addcheck//"`
pass=`echo "$pass" | sed "s/$portcheck//"`



#ЗАПУСК ПРИЛОЖЕНИЯ И НАБЛЮДЕНИЕ ЗА ХОДОМ РАБОТЫ
#Запускаем приложение с нужными параметрами
case $binFile in

	"VNC")
		binFile="$appfolder/vnc/vncviewer"
		config=" -config $appfolder/vnc/config/$hostName.vnc"
		TrackBinFile "VNC" "$binFile" "$config" 3
		;;
	"KIT")
		binFile="$appfolder/kitty/putty"
		[ $port != 22 ] && { port=$(($port - 1)); }
		config=" root@$address -P $port -pw $pass"
		TrackBinFile "Putty" "$binFile" "$config" 4
		;;
	"SCP")
		binFile="$appfolder/winscp/filezilla"
		[ $port != 22 ] && { port=$(($port - 2)); }
		config=" sftp://root:$pass@$address:$port"
		TrackBinFile "FileZilla" "$binFile" "$config" 5
		;;
	*)
		message=`echo -e "🛑<b>Ошибка конфигурации</b>\n️❌Ошибка в ссылке на схеме\n🖥️$hostName ⏱$(_Now)"`
		BotMsg "$message" 0
		message=`printf "%-19s" "$(_Now) | При запуске $binFile произошла ошибка. Проверьте схему, записи и диск GetStand"`
		echo -e	"$message" >> "$appfolder/httpN/system/log/system.txt"
		zenity --error --title="Ошибка" --window-icon="$icon/GetStand.png" --text="Ошибка запуска приложения\nОбратитесь в Отдел Тестирования" --ellipsize --timeout=3
		exit
		;;

esac