#!/bin/bash

#download
#realpath
#zenity
#curl pkexec
#vncviewer putty filezilla
#для китти ссылку в .putty на каталог с конфигами
#нужно править конфиг + вытягивать пароль
#scp sitemanager.xml ссылка


#Данные для телеграмм бота
sBotKey='bot1844208783:AAHnDQhkV7kARiLCyus0vxV8jQdAYy4TZcY' #Ваш api ключ
nChatId='-1001460258261'									#Id получателя
username=`hostname`



function BotMsg {					#функция отправки сообщений боту в телеграм

	local URL="https://api.telegram.org/$1/sendMessage"
	curl -s -X POST $URL -d chat_id=$2 -d parse_mode=html -d disable_notification=$3 -d text="$4"

}

function Format {					#Функция форматированного вывода

	printf "%-$1s" "$2" 

}

function _Now {						#функция генерации текущего времени

	echo $(date +"%d.%m.%Y %H:%M:%S")

}

function Logger {					#функция отправки текста в логи

	if [ $2 == 1 ]		#Запись лога запусков приложений
	then

		local tmpPath=$appfolder/system/log/log.txt	#Путь до лога
		local TIME=$(Format 19 "`_Now`")
		local USER=$(Format 42 "$3")
		local ADDRES=$(Format 21 "$4")
		local ACT=$(Format 35 "$1")
		echo "$TIME | $USER | $ADDRES | $ACT | $5" >> $tmpPath

	else				#Запись системного лога

		echo $(Format 19 "`_Now`") "| $1" >> $appfolder/system/log/system.txt

	fi

}

function FileReader {				#функция поиска строки в файле	

	local sText="$1"				#Список строк
	local sSearchText="$2"			#Искомая строка
	while IFS= read -r line			#Перебираем строки
	do

		[ -z "`echo $line | grep $sSearchText`" ] || {
			#Если есть совпадение, выдаем строку
			auth=`echo $line | egrep -o "\w+[-]{0,1}\w{0,}" | head -1`
			[ $auth == $sSearchText ] || { continue; }
			echo $line

		}

	done < $sText

}

function Validator {				#Функция проверки строки по шаблону

	if [ "$#" = 2 ]		#Если второго аргумента нет, пропускаем
	then

		if [ -z `echo "$1" | egrep -o "$2"` ]
		then

			echo 1

		else echo 0
		fi

	else echo 0
	fi

}

function AddrToMask {				#Функция преобразования адреса в маску

	case "$1" in			#Проверяем последние актеты на 0
		`echo $1 | egrep -o "(([0-9]{1,3}\.){1}[0].[0].[0])"`)
		echo 255.0.0.0		#Возвращаем маску
		;;
		`echo $1 | egrep -o "(([0-9]{1,3}\.){2}[0].[0])"`)
		echo 255.255.0.0
		;;
		`echo $1 | egrep -o "(([0-9]{1,3}\.){3}[0])"`)
		echo 255.255.255.0
		;;
		*)
		echo 255.255.255.255
		;;
	esac

}

function ConsolePing {				#Функция пинга

	#sleep 1s		#Без паузы почему то нормально не пингуется
	ping -c 3 -W 1 $1 >/dev/null
	echo $?

}

function RouteAddDel {				#Функция создания маршрута

	[ $1 = 1 ] && {

		pkexec route $2

	}

}

function TrackBinFile {				#Функция запуска и слежения за приложением

	#Выделяем имя пользователя из строки, которое будет использоваться в названии файлов
	name=`echo $autorizedUser | egrep -o "[а-яА-Я]{1,}\s{1,}[а-яА-Я]{1,}\(\w+\)"`
	RouteAddDel $4 "add -net $maskAddr netmask $gatemask gw $gateway"	#Строим маршрут если он есть
	if [[ `ConsolePing $address` != 0 ]]	#Проверяем сеть. Если не пингуется
	then

		message=`echo -e "👤$name\n️⚠️Неудачное подключение\n🖥️$hostName 🕹$1 ⏱$(_Now)"`
		BotMsg $sBotKey $nChatId 1 "$message"
		Logger "Хост не отвечает" 1 "$name" "$username" "$hostName:$1"
		zenity --error --title=Ошибка --ellipsize --text="Не удается подключиться к хосту.\nОбратитесь в Отдел Тестирования." --timeout=3

	else

		$2$3$hostName$5	&					#Запускаем приложение и фиксируем его PID
		PID=$!
		message=`echo -e "👤$name\n️✅Подключился к хосту\n🖥️$hostName 🕹$1 ⏱$(_Now)"`
		BotMsg $sBotKey $nChatId 1 "$message"
		Logger "Успешное подключение" 1 "$name" "$username" "$hostName:$1"
		#Запускаем сессию приложения
		t=0
		while true
		do

			sleep 1s						#Отсчитываем условную секунду
			t=$(($t + 1))
			#Условия окончания сессии
			if [ -z `ps --no-headers $PID` ]	#Если завершили процесс вручную
			then

				message=`echo -e "👤$name\n️⬅️Отключился от хоста\n🖥️$hostName 🕹$1 ⏱$(_Now)"`
				BotMsg $sBotKey $nChatId 1 "$message"
				Logger "Завершение работы" 1 "$name" "$username" "$hostName:$1"
				break

			elif [ -e $appfolder/system/temp/Sessions/UPDATE ]	#Если начали обновление
			then

				zenity --warning --title=Предупреждение --text="Обновление системы. Сохраните работу.\nПриложение закроется через минуту." --ellipsize --timeout=5
				j=0
				while [ $j -lt 55 ]
				do

					sleep 1s
					j=$(($j + 1))
					[ -z `ps --no-headers $PID` ] && { break; }
					[ -e "$appfolder/system/temp/Sessions/KILL" ] && { break; }

				done
				kill -9 $PID
				break

			elif [ $t == 30000 ]		#Если дождались таймаута
			then

				kill -9 $PID
				message=`echo -e "👤$name\n️⬅️Сессия завершена\n🖥️$hostName 🕹$1 ⏱$(_Now)"`
				BotMsg $sBotKey $nChatId 1 "$message"
				Logger "Сессия завершена" 1 "$name" "$username" "$hostName:$1"
				zenity --warning --title=Предупреждение --ellipsize --text="Сессия $hostName:$1\nзавершена по таймауту" --timeout=3

			fi

			#Функции, действующие во время сессии
			[ -e $appfolder/system/temp/Sessions/ONLINE ] && {			#Говорим что онлайн

				#Создаем файлик-метку, обрабатываем его другой прогой, которая его удалит
				touch "$appfolder/system/temp/PIDS/$name.$hostName.$(($t/60))"

			}

		done

	fi

	#Когда закончили работу или не смогли подключиться, нужно удалить маршрут за собой
	zenity --warning --text=`pgrep -f httpN_Linux | wc -w`
	[ `pgrep -f httpN_Linux | wc -w` -le 2 ] && {	#Если файл один (наш файл)

		zenity --warning --text=lol
		RouteAddDel $4 "del -net $maskAddr netmask $gatemask gw $gateway" #Удаляем построенный маршрут после окончания работы

	}

}